### ISSUE TITLE
Update Sainath.txt 

### ISSUE THREAD

**Issue by SainathPoojary** [saumya1singh/DemoWebsite#30] opened 2021-03-10 13:27 UTC
Hey @SaumyaSingh1, I want to update Sainath.txt in "DemoWebsite/Assignments/" 
Please Assign it to me.

**Comment by SaumyaSingh1** [comment] 2021-03-10 13:28
sure

**Comment by SainathPoojary** [comment] 2021-03-10 16:22
Hey @SaumyaSingh1, the Person to whom the issue is assigned, does he is responsible for Closing the issue or the owner will do it.

**Comment by SaumyaSingh1** [comment] 2021-03-12 02:49
Hi @SainathPoojary! 

If the issue is no more needed or is solved and you both know/understand this then either of them can do. 
For now, let the owner handle all these things, sounds good?

**Comment by SaumyaSingh1** [comment] 2021-03-12 02:50
Do you want me to close this issue :)? @SainathPoojary

**Closed** 2022-10-05 15:38 UTC
